// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportXLSX(arg1) {
  return window['go']['main']['App']['ExportXLSX'](arg1);
}

export function GenerateSchedule(arg1) {
  return window['go']['main']['App']['GenerateSchedule'](arg1);
}

export function LoadMonthData(arg1, arg2) {
  return window['go']['main']['App']['LoadMonthData'](arg1, arg2);
}

export function LoadPeople() {
  return window['go']['main']['App']['LoadPeople']();
}

export function SaveExportFile(arg1, arg2) {
  return window['go']['main']['App']['SaveExportFile'](arg1, arg2);
}

export function SaveMonthData(arg1) {
  return window['go']['main']['App']['SaveMonthData'](arg1);
}

export function SavePeople(arg1) {
  return window['go']['main']['App']['SavePeople'](arg1);
}

export function UpdateShiftEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateShiftEntry'](arg1, arg2, arg3, arg4);
}
